#!/usr/bin/python
# -*- coding: utf-8 -*-

# Enigma machine settings

# folders
ROTOR_DIR = r'rotors'

# letters supported by the machine
LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

# original rotor settings
#              pins: ABCDEFGHIJKLMNOPQRSTUVWXYZ
ROTOR_1_SETTINGS = ('EKMFLGDQVZNTOWYHXUSPAIBRCJ', 'R')
ROTOR_2_SETTINGS = ('AJDKSIRUXBLHWTMCQGZNPYFVOE', 'F')
ROTOR_3_SETTINGS = ('BDFHJLCPRTXVZNYEIWGAKMUSQO', 'W')
ROTOR_4_SETTINGS = ('ESOVPZJAYQUIRHXLNFTGKDCMWB', 'K')
ROTOR_5_SETTINGS = ('VZBRGITYUPSDNHLXAWMJQOFECK', 'A')

ROTORS = (ROTOR_1_SETTINGS, ROTOR_2_SETTINGS, ROTOR_3_SETTINGS, ROTOR_4_SETTINGS, ROTOR_5_SETTINGS)

TEST_ROTOR = ('ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'X')

# original reflector setings

REFLECTOR_B_SETTINGS = 'YRUHQSLDPXNGOKMIEBFZCWVJAT'
REFLECTOR_C_SETTINGS = 'FVPJIAOYEDRZXWGCTKUQSBNMHL'

TEST_REFLECTOR = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
